# Generated by Django 5.0.4 on 2024-06-13 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_area', models.CharField(max_length=200)),
                ('location_name', models.CharField(max_length=200)),
                ('embarcation_text', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('school', 'School'), ('residential', 'Residential')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RideSharing.locations')),
            ],
        ),
    ]
