# Generated by Django 5.0.4 on 2024-06-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0003_trips_round_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='round_trip',
        ),
    ]
