# Generated by Django 5.0.4 on 2024-08-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0007_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='system_message',
            field=models.BooleanField(default=True),
        ),
    ]
