# Generated by Django 5.0.4 on 2024-08-28 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0009_messages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='underlying_booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RideSharing.spot_bookings'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='underlying_trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RideSharing.trips'),
            preserve_default=False,
        ),
    ]
