# Generated by Django 5.0.4 on 2024-08-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSharing', '0010_messages_underlying_booking_messages_underlying_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_type',
            field=models.CharField(choices=[('approval', 'Approval'), ('rejection', 'Rejection'), ('request', 'Request'), ('info', 'Info')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
